debug: shell.c promptline.c parseline.c
	gcc shell.c promptline.c parseline.c -o debug -Wall -Wextra -g -DDEBUG
release: shell.c promptline.c parseline.c
	gcc shell.c promptline.c parseline.c -o release -Wall -Wextra -O2
