main: shell.c promptline.c parseline.c
	gcc shell.c promptline.c parseline.c -o shell -Wall -Wextra -g -DDEBUG
release: shell.c promptline.c parseline.c
	gcc shell.c promptline.c parseline.c -o shell -Wall -Wextra
