#!/usr/bin/bash
# Early exit on fail test
set -e

echo ""
echo "Simple cat"
./run_test -t simple_test

echo ""
echo "Simple cat with redirect to file"
./run_test -e testfile.txt -a test_output.txt -t test_to_file
rm test_output.txt

echo ""
echo "Simple cat with redirect to file and append"
./run_test -e testfile_double.txt -a test_output.txt -t test_append_file
rm test_output.txt

echo ""
echo "Grep with redirect from file"
./run_test -t test_from_file

echo ""
echo "Grep with redirect from file to file"
./run_test -a test_output.txt -e testfile_last.txt -t test_from_to_file
rm test_output.txt

echo ""
echo "Grep with redirect from file append file"
./run_test -a test_output.txt -e testfile_last_double.txt -t test_from_append_file
rm test_output.txt

echo ""
echo "Grep with redirect to file from file"
./run_test -a test_output.txt -e testfile_last.txt -t test_to_from_file
rm test_output.txt
